name: Go Build 

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.22' # The Go version to download (if necessary) and use.
    - name: build server
      shell: bash
      run: |
        cd go
        APP_PREFIX=privapps-notebook-server
        bash go-build.bash $APP_PREFIX
        for i in `ls $APP_PREFIX-*` ; do gzip -9 $i ; done
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      shell: bash
      run: |
        cd go-docker
        cp ../go/privapps-notebook-server-linux-*.gz .
        gzip -d *.gz &
        cp ../php/config.json .
        find .
        wget https://github.com/privapps/notebook/releases/download/v1.2.0/notebook.tar.gz
        tar xf notebook.tar.gz && mv notebook static
        wait
        docker buildx create --use
        docker buildx build --platform=linux/amd64,linux/arm64 .  -t ghcr.io/${{ github.repository_owner }}/notebook:${GITHUB_REF##*/} --push
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          go/privapps-notebook-server-darwin-amd64.gz
          go/privapps-notebook-server-darwin-arm64.gz
          go/privapps-notebook-server-linux-amd64.gz
          go/pvprivapps-notebook-server-linux-arm64.gz
          go/privapps-notebook-server-windows-amd64.exe.gz